# 📊 Ad Campaign Insights Dashboard

This notebook loads ad campaign data, computes key metrics (CTR, CPC, CPA), and displays insights for optimization.

In [2]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("ad_campaign_data.csv")

# Preview data
df.head()

,Campaign_ID,Campaign_Name,Date,Channel,Impressions,Clicks,Conversions,Cost
0,CID001,YouTube Ads - Fashion,2024-02-05,YouTube,20260,1317,17,1683.03
1,CID002,Search Ads - Shoes,2024-01-10,Display Network,5859,557,23,741.06
2,CID003,YouTube Ads - Fashion,2024-01-25,YouTube,32495,1562,37,913.64
3,CID004,Display Ads - Bags,2024-02-08,Display Network,23501,599,22,124.10
4,CID005,YouTube Ads - Fashion,2024-02-04,Google Search,35766,1451,36,801.02

In [3]:
# Calculate performance metrics
df['CTR'] = (df['Clicks'] / df['Impressions']) * 100
df['CPC'] = df['Cost'] / df['Clicks']
df['CPA'] = df['Cost'] / df['Conversions']

# Round values
df[['CTR', 'CPC', 'CPA']] = df[['CTR', 'CPC', 'CPA']].round(2)

# Preview updated DataFrame
df.head()

,Campaign_ID,Campaign_Name,Date,Channel,Impressions,Clicks,Conversions,Cost,CTR,CPC,CPA
0,CID001,YouTube Ads - Fashion,2024-02-05,YouTube,20260,1317,17,1683.03,6.50,1.28,99.00
1,CID002,Search Ads - Shoes,2024-01-10,Display Network,5859,557,23,741.06,9.51,1.33,32.22
2,CID003,YouTube Ads - Fashion,2024-01-25,YouTube,32495,1562,37,913.64,4.81,0.58,24.69
3,CID004,Display Ads - Bags,2024-02-08,Display Network,23501,599,22,124.10,2.55,0.21,5.64
4,CID005,YouTube Ads - Fashion,2024-02-04,Google Search,35766,1451,36,801.02,4.06,0.55,22.25

In [4]:
# Group by Campaign and summarize
summary = df.groupby('Campaign_Name').agg({
    'Impressions': 'sum',
    'Clicks': 'sum',
    'Conversions': 'sum',
    'Cost': 'sum',
    'CTR': 'mean',
    'CPC': 'mean',
    'CPA': 'mean'
}).round(2).sort_values(by='Conversions', ascending=False)

summary

,Impressions,Clicks,Conversions,Cost,CTR,CPC,CPA
Campaign_Name,,,,,,,
YouTube Ads - Fashion,605810,31715,918,35516.95,5.51,3.46,58.46
Display Ads - Accessories,508392,25744,573,25814.19,4.88,3.27,63.67
Display Ads - Bags,551414,31451,527,23938.12,5.52,1.84,75.88
Search Ads - Shoes,339128,18216,376,19522.76,5.66,3.49,86.87
Search Ads - Watches,355109,21094,328,19725.40,5.78,2.30,83.61

In [5]:
# Basic insights
top_ctr = summary.sort_values(by='CTR', ascending=False).head(3)
lowest_roi = summary.sort_values(by='CPA', ascending=False).head(3)

print("🔼 Top 3 Campaigns by CTR:")
display(top_ctr)

print("\n🔻 Bottom 3 Campaigns by ROI (High CPA):")
display(lowest_roi)

🔼 Top 3 Campaigns by CTR:

,Impressions,Clicks,Conversions,Cost,CTR,CPC,CPA
Campaign_Name,,,,,,,
Search Ads - Watches,355109,21094,328,19725.40,5.78,2.30,83.61
Search Ads - Shoes,339128,18216,376,19522.76,5.66,3.49,86.87
Display Ads - Bags,551414,31451,527,23938.12,5.52,1.84,75.88

🔻 Bottom 3 Campaigns by ROI (High CPA):

,Impressions,Clicks,Conversions,Cost,CTR,CPC,CPA
Campaign_Name,,,,,,,
Search Ads - Shoes,339128,18216,376,19522.76,5.66,3.49,86.87
Search Ads - Watches,355109,21094,328,19725.40,5.78,2.30,83.61
Display Ads - Bags,551414,31451,527,23938.12,5.52,1.84,75.88

You can now create charts in Tableau or Looker Studio using this data to build an interactive dashboard.